### ISSUE TITLE
EthereumListener > Cannot connect to MSSQL server from inside container

### ISSUE THREAD

**Issue by ThangCertipath** [CertiPath/DLTGateway#33]
Traceback (most recent call last):                                                                                                                                            File "src/pymssql.pyx", line 636, in pymssql.connect                                                                                                                        File "src/_mssql.pyx", line 1957, in _mssql.connect                                                                                                                         File "src/_mssql.pyx", line 676, in _mssql.MSSQLConnection.__init__                                                                                                         File "src/_mssql.pyx", line 1683, in _mssql.maybe_raise_MSSQLDatabaseException                                                                                            _mssql.MSSQLDatabaseException: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost:1433)\nNet-Lib error during Connection refused (111)\n')

**Comment by ThangCertipath** [comment]
Steps to resolve:
 - Find out the IP of the host machine on DocketNAT subnet.
 - Change the connection string to using the host's IP address on the DockerNAT.
 - Config SQLServer to enable TCP connection at the IP address on the DocketNAT.

**Comment by ThangCertipath** [comment]
Additionally, it is necessary to set the DockerNAT as a private network and then adjust Windows' firewall rules to allow connection from private network.

The powershell command for setting DockerNAT as a private network:

```Powershell
Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private
```

Source: https://github.com/docker/for-win/issues/367
